#include "compiler/llvm_emitter.hpp"
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <iostream>

namespace setun {

LLVMEmitter::LLVMEmitter(TargetConfig config)
    : config_(std::move(config)) {}

// ============================================================================
// 1. C20 SIMD Transpiler (Milestone 1: Baseline Ground-Truth)
// ============================================================================

static std::string type_to_c(DataType t) {
    switch (t) {
        case DataType::INT: return "int64_t";
        case DataType::TRYTE: return "int16_t";
        case DataType::BOOL: return "bool";
        case DataType::STRING: return "std::string";
        case DataType::FLOAT: return "double";
        case DataType::TAF3: return "TafpuNum_C";
        case DataType::VOID: return "void";
        default: return "auto";
    }
}

std::string LLVMEmitter::emit_native_c(const Program& program) {
    std::ostringstream oss;

    // Standard headers and runtime
    oss << "// ============================================================================\n";
    oss << "// Automatically generated by Setun 2.0 Native AOT Transpiler\n";
    oss << "// Target: " << config_.triple << " (Opt Level: -O" << config_.opt_level << ")\n";
    oss << "// ============================================================================\n\n";

    oss << "#include \"compiler/native_runtime.hpp\"\n";
    oss << "#include <iostream>\n";
    oss << "#include <string>\n";
    oss << "#include <cstdint>\n";
    oss << "#include <cassert>\n\n";
    oss << "using namespace setun::runtime;\n\n";

    // Forward declarations and struct/class definitions
    bool has_user_main = false;
    DataType user_main_ret = DataType::VOID;
    for (Stmt* s : program.statements) {
        if (std::holds_alternative<FnDeclStmt>(s->data)) {
            const auto& fn = std::get<FnDeclStmt>(s->data);
            std::string fname = (fn.name == "main") ? "stn_main" : fn.name;
            if (fn.name == "main") {
                has_user_main = true;
                user_main_ret = fn.return_type;
            }
            std::string ret_type = (fn.return_type == DataType::VOID) ? "void" :
                                   (fn.return_type == DataType::ANY ? "auto" : type_to_c(fn.return_type));
            oss << ret_type << " " << fname << "(";
            for (size_t i = 0; i < fn.params.size(); ++i) {
                if (i > 0) oss << ", ";
                std::string ptype = type_to_c(fn.params[i].type);
                if (ptype == "std::string") ptype = "const std::string&";
                oss << ptype << " " << fn.params[i].name;
            }
            oss << ");\n";
        }
    }
    oss << "\n";

    // Emit global statements and functions
    std::vector<Stmt*> main_stmts;
    for (Stmt* s : program.statements) {
        if (std::holds_alternative<FnDeclStmt>(s->data)) {
            transpile_stmt(s, oss, 0);
            oss << "\n";
        } else {
            main_stmts.push_back(s);
        }
    }

    // Main entry point
    oss << "int main(int argc, char** argv) {\n";
    oss << "    (void)argc; (void)argv;\n";
    oss << "    // Setun Native Execution Entry\n";
    for (Stmt* s : main_stmts) {
        transpile_stmt(s, oss, 1);
    }
    if (has_user_main) {
        if (user_main_ret == DataType::TAF3) {
            oss << "    return static_cast<int>(stn_main().a);\n";
        } else if (user_main_ret == DataType::VOID) {
            oss << "    stn_main();\n    return 0;\n";
        } else {
            oss << "    return static_cast<int>(stn_main());\n";
        }
    } else {
        oss << "    return 0;\n";
    }
    oss << "}\n";

    return oss.str();
}

void LLVMEmitter::transpile_stmt(Stmt* stmt, std::ostringstream& oss, int indent) {
    if (!stmt) return;
    std::string pad(indent * 4, ' ');

    std::visit([&](const auto& s) {
        using T = std::decay_t<decltype(s)>;

        if constexpr (std::is_same_v<T, VarDeclStmt>) {
            std::string c_type = (s.type == DataType::ANY) ? "auto" : type_to_c(s.type);
            oss << pad << c_type << " " << s.name << " = ";
            if (s.init) {
                transpile_expr(s.init, oss);
            } else {
                if (c_type == "int64_t" || c_type == "int16_t") oss << "0";
                else if (c_type == "bool") oss << "false";
                else if (c_type == "std::string") oss << "\"\"";
                else if (c_type == "double") oss << "0.0";
                else oss << "TafpuNum_C(0, 0, 0)";
            }
            oss << ";\n";
        }
        else if constexpr (std::is_same_v<T, AssignStmt>) {
            oss << pad << s.name << " = ";
            transpile_expr(s.value, oss);
            oss << ";\n";
        }
        else if constexpr (std::is_same_v<T, MemberAssignStmt>) {
            oss << pad;
            transpile_expr(s.object, oss);
            oss << "." << s.member << " = ";
            transpile_expr(s.value, oss);
            oss << ";\n";
        }
        else if constexpr (std::is_same_v<T, IndexAssignStmt>) {
            oss << pad;
            transpile_expr(s.object, oss);
            oss << "[";
            transpile_expr(s.index, oss);
            oss << "] = ";
            transpile_expr(s.value, oss);
            oss << ";\n";
        }
        else if constexpr (std::is_same_v<T, ExprStmt>) {
            oss << pad;
            transpile_expr(s.expr, oss);
            oss << ";\n";
        }
        else if constexpr (std::is_same_v<T, BlockStmt>) {
            oss << pad << "{\n";
            for (Stmt* child : s.statements) {
                transpile_stmt(child, oss, indent + 1);
            }
            oss << pad << "}\n";
        }
        else if constexpr (std::is_same_v<T, IfStmt>) {
            oss << pad << "if (";
            transpile_expr(s.condition, oss);
            oss << ".to_double() != 0.0) {\n";
            transpile_stmt(s.then_branch, oss, indent + 1);
            oss << pad << "}";
            if (s.else_branch) {
                oss << " else {\n";
                transpile_stmt(s.else_branch, oss, indent + 1);
                oss << pad << "}";
            }
            oss << "\n";
        }
        else if constexpr (std::is_same_v<T, Branch3Stmt>) {
            oss << pad << "{\n";
            oss << pad << "    int __sign = tafpu_cmp_c(";
            transpile_expr(s.condition, oss);
            oss << ", TafpuNum_C(0, 0, 0));\n";
            oss << pad << "    switch (__sign) {\n";
            oss << pad << "        case -1: {\n";
            if (s.neg_branch) transpile_stmt(s.neg_branch, oss, indent + 3);
            oss << pad << "            break;\n";
            oss << pad << "        }\n";
            oss << pad << "        case 0: {\n";
            if (s.zero_branch) transpile_stmt(s.zero_branch, oss, indent + 3);
            oss << pad << "            break;\n";
            oss << pad << "        }\n";
            oss << pad << "        case 1: {\n";
            if (s.pos_branch) transpile_stmt(s.pos_branch, oss, indent + 3);
            oss << pad << "            break;\n";
            oss << pad << "        }\n";
            oss << pad << "    }\n";
            oss << pad << "}\n";
        }
        else if constexpr (std::is_same_v<T, MatchStmt>) {
            oss << pad << "{\n";
            oss << pad << "    TafpuNum_C __match_val = ";
            transpile_expr(s.condition, oss);
            oss << ";\n";
            for (size_t i = 0; i < s.arms.size(); ++i) {
                const auto& arm = s.arms[i];
                oss << pad << "    " << (i == 0 ? "if" : "else if") << " (tafpu_cmp_c(__match_val, ";
                transpile_expr(arm.pattern, oss);
                oss << ") == 0";
                if (arm.guard) {
                    oss << " && (";
                    transpile_expr(arm.guard, oss);
                    oss << ".to_double() != 0.0)";
                }
                oss << ") {\n";
                transpile_stmt(arm.body, oss, indent + 2);
                oss << pad << "    }\n";
            }
            oss << pad << "}\n";
        }
        else if constexpr (std::is_same_v<T, WhileStmt>) {
            oss << pad << "while (";
            transpile_expr(s.condition, oss);
            oss << ".to_double() != 0.0) {\n";
            transpile_stmt(s.body, oss, indent + 1);
            oss << pad << "}\n";
        }
        else if constexpr (std::is_same_v<T, ReturnStmt>) {
            oss << pad << "return ";
            if (s.value) {
                transpile_expr(s.value, oss);
            } else {
                oss << "TafpuNum_C(0, 0, 0)";
            }
            oss << ";\n";
        }
        else if constexpr (std::is_same_v<T, FnDeclStmt>) {
            std::string fname = (s.name == "main") ? "stn_main" : s.name;
            std::string ret_type = (s.return_type == DataType::VOID) ? "void" : 
                                   (s.return_type == DataType::ANY ? "auto" : type_to_c(s.return_type));
            oss << ret_type << " " << fname << "(";
            for (size_t i = 0; i < s.params.size(); ++i) {
                if (i > 0) oss << ", ";
                std::string ptype = type_to_c(s.params[i].type);
                if (ptype == "std::string") ptype = "const std::string&";
                oss << ptype << " " << s.params[i].name;
            }
            oss << ") {\n";
            if (s.body) {
                transpile_stmt(s.body, oss, indent + 1);
            }
            if (ret_type == "void") {
                oss << "}\n";
            } else if (ret_type == "int64_t" || ret_type == "int16_t") {
                oss << "    return 0;\n}\n";
            } else if (ret_type == "bool") {
                oss << "    return false;\n}\n";
            } else if (ret_type == "std::string") {
                oss << "    return \"\";\n}\n";
            } else {
                oss << "    return TafpuNum_C(0, 0, 0);\n}\n";
            }
        }
        else if constexpr (std::is_same_v<T, StructDeclStmt>) {
            oss << pad << "// Struct " << s.name << " (Value Type)\n";
        }
        else if constexpr (std::is_same_v<T, ClassDeclStmt>) {
            oss << pad << "// Class " << s.name << " (Reference Type with ARC)\n";
        }
        else if constexpr (std::is_same_v<T, InterfaceDeclStmt>) {
            oss << pad << "// Interface " << s.name << "\n";
        }
        else if constexpr (std::is_same_v<T, EnumDeclStmt>) {
            oss << pad << "// Enum " << s.name << "\n";
        }
        else if constexpr (std::is_same_v<T, ImportStmt>) {
            oss << pad << "// Import " << s.module_path << "\n";
        }
    }, stmt->data);
}

void LLVMEmitter::transpile_expr(Expr* expr, std::ostringstream& oss) {
    if (!expr) return;

    std::visit([&](const auto& e) {
        using T = std::decay_t<decltype(e)>;

        if constexpr (std::is_same_v<T, IntLiteralExpr>) {
            oss << "TafpuNum_C(" << e.value << ", 0, 0)";
        }
        else if constexpr (std::is_same_v<T, TryteLiteralExpr>) {
            oss << "TafpuNum_C(" << e.value << ", 0, 0)";
        }
        else if constexpr (std::is_same_v<T, TafpuLiteralExpr>) {
            oss << "TafpuNum_C(" << e.value.a << ", " << e.value.b << ", " << e.value.s << ")";
        }
        else if constexpr (std::is_same_v<T, FloatLiteralExpr>) {
            oss << "TafpuNum_C(" << static_cast<int64_t>(e.value) << ", 0, 0)";
        }
        else if constexpr (std::is_same_v<T, StringLiteralExpr>) {
            oss << "std::string(\"" << e.value << "\")";
        }
        else if constexpr (std::is_same_v<T, BoolLiteralExpr>) {
            oss << (e.value ? "true" : "false");
        }
        else if constexpr (std::is_same_v<T, TafpuConstructExpr>) {
            oss << "TafpuNum_C(";
            transpile_expr(e.a, oss); oss << ".a, ";
            transpile_expr(e.b, oss); oss << ".a, ";
            transpile_expr(e.s, oss); oss << ".a)";
        }
        else if constexpr (std::is_same_v<T, IdentifierExpr>) {
            oss << e.name;
        }
        else if constexpr (std::is_same_v<T, MemberAccessExpr>) {
            transpile_expr(e.object, oss);
            oss << "." << e.member;
        }
        else if constexpr (std::is_same_v<T, MethodCallExpr>) {
            transpile_expr(e.object, oss);
            oss << "." << e.method << "(";
            for (size_t i = 0; i < e.args.size(); ++i) {
                if (i > 0) oss << ", ";
                transpile_expr(e.args[i], oss);
            }
            oss << ")";
        }
        else if constexpr (std::is_same_v<T, IndexExpr>) {
            if (e.object) transpile_expr(e.object, oss);
            oss << "[";
            if (e.index) transpile_expr(e.index, oss);
            oss << "]";
        }
        else if constexpr (std::is_same_v<T, ArrayLiteralExpr>) {
            oss << "std::vector{";
            for (size_t i = 0; i < e.elements.size(); ++i) {
                if (i > 0) oss << ", ";
                transpile_expr(e.elements[i], oss);
            }
            oss << "}";
        }
        else if constexpr (std::is_same_v<T, UnaryExpr>) {
            if (e.op == UnaryOp::NEG) {
                oss << "TafpuNum_C(-("; transpile_expr(e.operand, oss); oss << ").a, -(";
                transpile_expr(e.operand, oss); oss << ").b, (";
                transpile_expr(e.operand, oss); oss << ").s)";
            } else {
                transpile_expr(e.operand, oss);
            }
        }
        else if constexpr (std::is_same_v<T, BinaryExpr>) {
            switch (e.op) {
                case BinaryOp::ADD:
                    oss << "tafpu_add_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ")";
                    break;
                case BinaryOp::SUB:
                    oss << "tafpu_sub_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ")";
                    break;
                case BinaryOp::MUL:
                case BinaryOp::MATMUL:
                    oss << "tafpu_mul_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ")";
                    break;
                case BinaryOp::SPACESHIP:
                    oss << "TafpuNum_C(tafpu_cmp_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << "), 0, 0)";
                    break;
                case BinaryOp::EQ:
                    oss << "TafpuNum_C(tafpu_cmp_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ") == 0 ? 1 : 0, 0, 0)";
                    break;
                case BinaryOp::NEQ:
                    oss << "TafpuNum_C(tafpu_cmp_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ") != 0 ? 1 : 0, 0, 0)";
                    break;
                case BinaryOp::LT:
                    oss << "TafpuNum_C(tafpu_cmp_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ") < 0 ? 1 : 0, 0, 0)";
                    break;
                case BinaryOp::LE:
                    oss << "TafpuNum_C(tafpu_cmp_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ") <= 0 ? 1 : 0, 0, 0)";
                    break;
                case BinaryOp::GT:
                    oss << "TafpuNum_C(tafpu_cmp_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ") > 0 ? 1 : 0, 0, 0)";
                    break;
                case BinaryOp::GE:
                    oss << "TafpuNum_C(tafpu_cmp_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ") >= 0 ? 1 : 0, 0, 0)";
                    break;
                default:
                    oss << "tafpu_add_c("; transpile_expr(e.left, oss); oss << ", "; transpile_expr(e.right, oss); oss << ")";
                    break;
            }
        }
        else if constexpr (std::is_same_v<T, CallExpr>) {
            if (e.callee == "println" || e.callee == "print") {
                oss << "std::cout << ";
                if (!e.args.empty()) {
                    Expr* arg = e.args[0];
                    if (std::holds_alternative<StringLiteralExpr>(arg->data)) {
                        const auto& str = std::get<StringLiteralExpr>(arg->data);
                        oss << "\"" << str.value << "\"";
                    } else {
                        oss << "(";
                        transpile_expr(arg, oss);
                        oss << ").to_double()";
                    }
                }
                if (e.callee == "println") oss << " << '\\n'";
            } else if (e.callee == "assert_eq") {
                oss << "assert(tafpu_cmp_c(";
                transpile_expr(e.args[0], oss);
                oss << ", ";
                transpile_expr(e.args[1], oss);
                oss << ") == 0)";
            } else {
                oss << e.callee << "(";
                for (size_t i = 0; i < e.args.size(); ++i) {
                    if (i > 0) oss << ", ";
                    transpile_expr(e.args[i], oss);
                }
                oss << ")";
            }
        }
        else if constexpr (std::is_same_v<T, FStringExpr>) {
            oss << "TafpuNum_C(0, 0, 0) /* " << e.format_string << " */";
        }
        else if constexpr (std::is_same_v<T, ComptimeExpr>) {
            transpile_expr(e.expr, oss);
        }
    }, expr->data);
}

// ============================================================================
// 2. Multi-Arch LLVM IR Text Generator (.ll) & Direct Engine
// ============================================================================

std::string LLVMEmitter::next_label(const std::string& prefix) {
    return prefix + "_" + std::to_string(++label_counter_);
}

std::string LLVMEmitter::next_temp() {
    return "%t" + std::to_string(++temp_id_);
}

void LLVMEmitter::emit_llvm_global_decls(std::ostringstream& oss) {
    oss << "; ModuleID = 'setun_module'\n";
    oss << "source_filename = \"setun_source.stn\"\n";
    oss << "target datalayout = \"e-m:w-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128\"\n";
    oss << "target triple = \"" << config_.triple << "\"\n\n";

    oss << "%struct.TafpuNum = type { i64, i64, i32, i32 }\n";
    oss << "@TAFPU_ZERO = private unnamed_addr constant %struct.TafpuNum { i64 0, i64 0, i32 0, i32 0 }, align 8\n";
    oss << "@.fmt_i64 = private unnamed_addr constant [6 x i8] c\"%lld\\0A\\00\", align 1\n";
    oss << "@.fmt_str = private unnamed_addr constant [4 x i8] c\"%s\\0A\\00\", align 1\n\n";

    // External declarations
    oss << "declare i32 @printf(i8*, ...) nounwind\n";
    oss << "declare i32 @puts(i8*) nounwind\n";
    oss << "declare void @abort() noreturn nounwind\n";
    oss << "declare i32 @setun2d_init(i32, i32, i8*)\n";
    oss << "declare i32 @setun2d_is_running()\n";
    oss << "declare void @setun2d_clear(i32)\n";
    oss << "declare void @setun2d_draw_rect(i32, i32, i32, i32, i32)\n";
    oss << "declare void @setun2d_draw_circle(i32, i32, i32, i32)\n";
    oss << "declare void @setun2d_draw_text(i32, i32, i8*, i32)\n";
    oss << "declare i32 @setun2d_flip()\n";
    oss << "declare i32 @setun2d_get_key()\n";
    oss << "declare void @setun2d_close()\n\n";

    // BitNet 1.58-bit AI Engine Declarations
    oss << "declare i32 @setun_nn_create_dense(i32, i32, i32)\n";
    oss << "declare void @setun_nn_set_weight(i32, i32, i32, i32)\n";
    oss << "declare void @setun_nn_set_bias(i32, i32, i64)\n";
    oss << "declare void @setun_nn_set_input(i32, i64)\n";
    oss << "declare i64 @setun_nn_get_input(i32)\n";
    oss << "declare void @setun_nn_forward(i32)\n";
    oss << "declare i64 @setun_nn_get_output(i32, i32)\n";
    oss << "declare void @setun_nn_copy_output_to_input(i32)\n";
    oss << "declare i32 @setun_nn_predict(i32)\n";
    oss << "declare i32 @setun_nn_get_confidence(i32, i32)\n";
    oss << "declare void @setun_nn_load_mnist_sample(i32)\n";
    oss << "declare void @setun_nn_free_layer(i32)\n\n";

    // Native TAFPU Arithmetic Inlined
    oss << "define void @tafpu_add_native(%struct.TafpuNum* noalias nocapture sret(%struct.TafpuNum) %res, %struct.TafpuNum* nocapture readonly %x1, %struct.TafpuNum* nocapture readonly %x2) alwaysinline nounwind {\n";
    oss << "entry:\n";
    oss << "    %a1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 0\n";
    oss << "    %a1 = load i64, i64* %a1.ptr, align 8\n";
    oss << "    %b1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 1\n";
    oss << "    %b1 = load i64, i64* %b1.ptr, align 8\n";
    oss << "    %s1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 2\n";
    oss << "    %s1 = load i32, i32* %s1.ptr, align 4\n";
    oss << "    %a2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 0\n";
    oss << "    %a2 = load i64, i64* %a2.ptr, align 8\n";
    oss << "    %b2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 1\n";
    oss << "    %b2 = load i64, i64* %b2.ptr, align 8\n";
    oss << "    %a_res = add i64 %a1, %a2\n";
    oss << "    %b_res = add i64 %b1, %b2\n";
    oss << "    %res.a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 0\n";
    oss << "    store i64 %a_res, i64* %res.a, align 8\n";
    oss << "    %res.b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 1\n";
    oss << "    store i64 %b_res, i64* %res.b, align 8\n";
    oss << "    %res.s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 2\n";
    oss << "    store i32 %s1, i32* %res.s, align 4\n";
    oss << "    ret void\n";
    oss << "}\n\n";

    oss << "define void @tafpu_sub_native(%struct.TafpuNum* noalias nocapture sret(%struct.TafpuNum) %res, %struct.TafpuNum* nocapture readonly %x1, %struct.TafpuNum* nocapture readonly %x2) alwaysinline nounwind {\n";
    oss << "entry:\n";
    oss << "    %a1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 0\n";
    oss << "    %a1 = load i64, i64* %a1.ptr, align 8\n";
    oss << "    %b1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 1\n";
    oss << "    %b1 = load i64, i64* %b1.ptr, align 8\n";
    oss << "    %s1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 2\n";
    oss << "    %s1 = load i32, i32* %s1.ptr, align 4\n";
    oss << "    %a2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 0\n";
    oss << "    %a2 = load i64, i64* %a2.ptr, align 8\n";
    oss << "    %b2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 1\n";
    oss << "    %b2 = load i64, i64* %b2.ptr, align 8\n";
    oss << "    %a_res = sub i64 %a1, %a2\n";
    oss << "    %b_res = sub i64 %b1, %b2\n";
    oss << "    %res.a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 0\n";
    oss << "    store i64 %a_res, i64* %res.a, align 8\n";
    oss << "    %res.b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 1\n";
    oss << "    store i64 %b_res, i64* %res.b, align 8\n";
    oss << "    %res.s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 2\n";
    oss << "    store i32 %s1, i32* %res.s, align 4\n";
    oss << "    ret void\n";
    oss << "}\n\n";

    oss << "define void @tafpu_mul_native(%struct.TafpuNum* noalias nocapture sret(%struct.TafpuNum) %res, %struct.TafpuNum* nocapture readonly %x1, %struct.TafpuNum* nocapture readonly %x2) alwaysinline nounwind {\n";
    oss << "entry:\n";
    oss << "    %a1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 0\n";
    oss << "    %a1 = load i64, i64* %a1.ptr, align 8\n";
    oss << "    %b1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 1\n";
    oss << "    %b1 = load i64, i64* %b1.ptr, align 8\n";
    oss << "    %s1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 2\n";
    oss << "    %s1 = load i32, i32* %s1.ptr, align 4\n";
    oss << "    %a2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 0\n";
    oss << "    %a2 = load i64, i64* %a2.ptr, align 8\n";
    oss << "    %b2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 1\n";
    oss << "    %b2 = load i64, i64* %b2.ptr, align 8\n";
    oss << "    %s2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 2\n";
    oss << "    %s2 = load i32, i32* %s2.ptr, align 4\n";
    oss << "    %a1a2 = mul i64 %a1, %a2\n";
    oss << "    %b1b2 = mul i64 %b1, %b2\n";
    oss << "    %b1b2_3 = mul i64 %b1b2, 3\n";
    oss << "    %a_res = add i64 %a1a2, %b1b2_3\n";
    oss << "    %a1b2 = mul i64 %a1, %b2\n";
    oss << "    %b1a2 = mul i64 %b1, %a2\n";
    oss << "    %b_res = add i64 %a1b2, %b1a2\n";
    oss << "    %s_res = add i32 %s1, %s2\n";
    oss << "    %res.a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 0\n";
    oss << "    store i64 %a_res, i64* %res.a, align 8\n";
    oss << "    %res.b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 1\n";
    oss << "    store i64 %b_res, i64* %res.b, align 8\n";
    oss << "    %res.s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %res, i32 0, i32 2\n";
    oss << "    store i32 %s_res, i32* %res.s, align 4\n";
    oss << "    ret void\n";
    oss << "}\n\n";

    oss << "define i32 @tafpu_cmp_native(%struct.TafpuNum* nocapture readonly %x1, %struct.TafpuNum* nocapture readonly %x2) alwaysinline nounwind {\n";
    oss << "entry:\n";
    oss << "    %a1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 0\n";
    oss << "    %a1 = load i64, i64* %a1.ptr, align 8\n";
    oss << "    %b1.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x1, i32 0, i32 1\n";
    oss << "    %b1 = load i64, i64* %b1.ptr, align 8\n";
    oss << "    %a2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 0\n";
    oss << "    %a2 = load i64, i64* %a2.ptr, align 8\n";
    oss << "    %b2.ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %x2, i32 0, i32 1\n";
    oss << "    %b2 = load i64, i64* %b2.ptr, align 8\n";
    oss << "    %diff_a = sub i64 %a1, %a2\n";
    oss << "    %diff_b = sub i64 %b1, %b2\n";
    oss << "    %da_flt = sitofp i64 %diff_a to double\n";
    oss << "    %db_flt = sitofp i64 %diff_b to double\n";
    oss << "    %db_rt3 = fmul double %db_flt, 0x3FFBB67AE8584CAA\n";
    oss << "    %val = fadd double %da_flt, %db_rt3\n";
    oss << "    %is_gt = fcmp ogt double %val, 0.00001\n";
    oss << "    %is_lt = fcmp olt double %val, -0.00001\n";
    oss << "    %res_gt = select i1 %is_gt, i32 1, i32 0\n";
    oss << "    %res = select i1 %is_lt, i32 -1, i32 %res_gt\n";
    oss << "    ret i32 %res\n";
    oss << "}\n\n";
}

void LLVMEmitter::emit_llvm_function(Stmt* stmt, std::ostringstream& oss) {
    if (!stmt || !std::holds_alternative<FnDeclStmt>(stmt->data)) return;
    const auto& fn = std::get<FnDeclStmt>(stmt->data);

    std::string fname = (fn.name == "main") ? "stn_main" : fn.name;
    current_res_ptr_ = "%res";

    oss << "define void @" << fname << "(%struct.TafpuNum* noalias sret(%struct.TafpuNum) %res";
    for (size_t i = 0; i < fn.params.size(); ++i) {
        oss << ", %struct.TafpuNum* readonly %param_" << fn.params[i].name;
    }
    oss << ") {\n";
    oss << "entry:\n";

    llvm_vars_.clear();
    for (size_t i = 0; i < fn.params.size(); ++i) {
        std::string var_ptr = "%" + fn.params[i].name + ".ptr";
        oss << "    " << var_ptr << " = alloca %struct.TafpuNum, align 8\n";
        oss << "    %p_" << i << ".a_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %param_" << fn.params[i].name << ", i32 0, i32 0\n";
        oss << "    %p_" << i << ".a = load i64, i64* %p_" << i << ".a_ptr, align 8\n";
        oss << "    %p_" << i << ".b_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %param_" << fn.params[i].name << ", i32 0, i32 1\n";
        oss << "    %p_" << i << ".b = load i64, i64* %p_" << i << ".b_ptr, align 8\n";
        oss << "    %p_" << i << ".s_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %param_" << fn.params[i].name << ", i32 0, i32 2\n";
        oss << "    %p_" << i << ".s = load i32, i32* %p_" << i << ".s_ptr, align 4\n";
        oss << "    %dst_" << i << ".a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 0\n";
        oss << "    store i64 %p_" << i << ".a, i64* %dst_" << i << ".a, align 8\n";
        oss << "    %dst_" << i << ".b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 1\n";
        oss << "    store i64 %p_" << i << ".b, i64* %dst_" << i << ".b, align 8\n";
        oss << "    %dst_" << i << ".s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 2\n";
        oss << "    store i32 %p_" << i << ".s, i32* %dst_" << i << ".s, align 4\n";
        llvm_vars_[fn.params[i].name] = var_ptr;
    }

    if (fn.body) {
        emit_llvm_stmt(fn.body, oss);
    }

    oss << "    ret void\n";
    oss << "}\n\n";
}

void LLVMEmitter::emit_llvm_stmt(Stmt* stmt, std::ostringstream& oss) {
    if (!stmt) return;

    std::visit([&](const auto& s) {
        using T = std::decay_t<decltype(s)>;

        if constexpr (std::is_same_v<T, VarDeclStmt>) {
            std::string var_ptr = "%" + s.name + ".ptr";
            oss << "    " << var_ptr << " = alloca %struct.TafpuNum, align 8\n";
            llvm_vars_[s.name] = var_ptr;

            if (s.init) {
                std::string init_ptr = emit_llvm_expr(s.init, oss);
                std::string t = next_temp();
                oss << "    " << t << ".a_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << init_ptr << ", i32 0, i32 0\n";
                oss << "    " << t << ".a = load i64, i64* " << t << ".a_ptr, align 8\n";
                oss << "    " << t << ".b_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << init_ptr << ", i32 0, i32 1\n";
                oss << "    " << t << ".b = load i64, i64* " << t << ".b_ptr, align 8\n";
                oss << "    " << t << ".s_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << init_ptr << ", i32 0, i32 2\n";
                oss << "    " << t << ".s = load i32, i32* " << t << ".s_ptr, align 4\n";

                oss << "    " << t << ".dst_a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 0\n";
                oss << "    store i64 " << t << ".a, i64* " << t << ".dst_a, align 8\n";
                oss << "    " << t << ".dst_b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 1\n";
                oss << "    store i64 " << t << ".b, i64* " << t << ".dst_b, align 8\n";
                oss << "    " << t << ".dst_s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 2\n";
                oss << "    store i32 " << t << ".s, i64* " << t << ".dst_s, align 4\n";
            }
        }
        else if constexpr (std::is_same_v<T, AssignStmt>) {
            auto it = llvm_vars_.find(s.name);
            if (it != llvm_vars_.end()) {
                std::string var_ptr = it->second;
                std::string val_ptr = emit_llvm_expr(s.value, oss);
                std::string t = next_temp();
                oss << "    " << t << ".a_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << val_ptr << ", i32 0, i32 0\n";
                oss << "    " << t << ".a = load i64, i64* " << t << ".a_ptr, align 8\n";
                oss << "    " << t << ".b_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << val_ptr << ", i32 0, i32 1\n";
                oss << "    " << t << ".b = load i64, i64* " << t << ".b_ptr, align 8\n";
                oss << "    " << t << ".s_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << val_ptr << ", i32 0, i32 2\n";
                oss << "    " << t << ".s = load i32, i32* " << t << ".s_ptr, align 4\n";

                oss << "    " << t << ".dst_a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 0\n";
                oss << "    store i64 " << t << ".a, i64* " << t << ".dst_a, align 8\n";
                oss << "    " << t << ".dst_b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 1\n";
                oss << "    store i64 " << t << ".b, i64* " << t << ".dst_b, align 8\n";
                oss << "    " << t << ".dst_s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << var_ptr << ", i32 0, i32 2\n";
                oss << "    store i32 " << t << ".s, i64* " << t << ".dst_s, align 4\n";
            }
        }
        else if constexpr (std::is_same_v<T, ExprStmt>) {
            emit_llvm_expr(s.expr, oss);
        }
        else if constexpr (std::is_same_v<T, BlockStmt>) {
            for (Stmt* sub_s : s.statements) {
                emit_llvm_stmt(sub_s, oss);
            }
        }
        else if constexpr (std::is_same_v<T, IfStmt>) {
            std::string cond_ptr = emit_llvm_expr(s.condition, oss);
            std::string t = next_temp();
            oss << "    " << t << ".a_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << cond_ptr << ", i32 0, i32 0\n";
            oss << "    " << t << ".a = load i64, i64* " << t << ".a_ptr, align 8\n";
            oss << "    " << t << ".cond = icmp ne i64 " << t << ".a, 0\n";

            std::string then_lbl = next_label("then");
            std::string else_lbl = next_label("else");
            std::string merge_lbl = next_label("merge");

            oss << "    br i1 " << t << ".cond, label %" << then_lbl << ", label %" << else_lbl << "\n";
            oss << then_lbl << ":\n";
            if (s.then_branch) emit_llvm_stmt(s.then_branch, oss);
            oss << "    br label %" << merge_lbl << "\n";

            oss << else_lbl << ":\n";
            if (s.else_branch) emit_llvm_stmt(s.else_branch, oss);
            oss << "    br label %" << merge_lbl << "\n";

            oss << merge_lbl << ":\n";
        }
        else if constexpr (std::is_same_v<T, WhileStmt>) {
            std::string cond_lbl = next_label("while_cond");
            std::string body_lbl = next_label("while_body");
            std::string exit_lbl = next_label("while_exit");

            oss << "    br label %" << cond_lbl << "\n";
            oss << cond_lbl << ":\n";
            std::string cond_ptr = emit_llvm_expr(s.condition, oss);
            std::string t = next_temp();
            oss << "    " << t << ".a_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << cond_ptr << ", i32 0, i32 0\n";
            oss << "    " << t << ".a = load i64, i64* " << t << ".a_ptr, align 8\n";
            oss << "    " << t << ".cond = icmp ne i64 " << t << ".a, 0\n";
            oss << "    br i1 " << t << ".cond, label %" << body_lbl << ", label %" << exit_lbl << "\n";

            oss << body_lbl << ":\n";
            if (s.body) emit_llvm_stmt(s.body, oss);
            oss << "    br label %" << cond_lbl << "\n";

            oss << exit_lbl << ":\n";
        }
        else if constexpr (std::is_same_v<T, Branch3Stmt>) {
            std::string cond_ptr = emit_llvm_expr(s.condition, oss);
            std::string t = next_temp();
            oss << "    " << t << ".trit = call i32 @tafpu_cmp_native(%struct.TafpuNum* " << cond_ptr << ", %struct.TafpuNum* @TAFPU_ZERO)\n";

            std::string neg_lbl = next_label("br3_neg");
            std::string zero_lbl = next_label("br3_zero");
            std::string pos_lbl = next_label("br3_pos");
            std::string merge_lbl = next_label("br3_merge");

            oss << "    switch i32 " << t << ".trit, label %" << zero_lbl << " [\n";
            oss << "        i32 -1, label %" << neg_lbl << "\n";
            oss << "        i32 1, label %" << pos_lbl << "\n";
            oss << "    ]\n";

            // Arm Negative
            oss << neg_lbl << ":\n";
            if (s.neg_branch) emit_llvm_stmt(s.neg_branch, oss);
            oss << "    br label %" << merge_lbl << "\n";

            // Arm Zero
            oss << zero_lbl << ":\n";
            if (s.zero_branch) emit_llvm_stmt(s.zero_branch, oss);
            oss << "    br label %" << merge_lbl << "\n";

            // Arm Positive
            oss << pos_lbl << ":\n";
            if (s.pos_branch) emit_llvm_stmt(s.pos_branch, oss);
            oss << "    br label %" << merge_lbl << "\n";

            oss << merge_lbl << ":\n";
        }
        else if constexpr (std::is_same_v<T, ReturnStmt>) {
            if (s.value && !current_res_ptr_.empty()) {
                std::string val_ptr = emit_llvm_expr(s.value, oss);
                std::string t = next_temp();
                oss << "    " << t << ".a_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << val_ptr << ", i32 0, i32 0\n";
                oss << "    " << t << ".a = load i64, i64* " << t << ".a_ptr, align 8\n";
                oss << "    " << t << ".b_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << val_ptr << ", i32 0, i32 1\n";
                oss << "    " << t << ".b = load i64, i64* " << t << ".b_ptr, align 8\n";
                oss << "    " << t << ".s_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << val_ptr << ", i32 0, i32 2\n";
                oss << "    " << t << ".s = load i32, i32* " << t << ".s_ptr, align 4\n";

                oss << "    " << t << ".dst_a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << current_res_ptr_ << ", i32 0, i32 0\n";
                oss << "    store i64 " << t << ".a, i64* " << t << ".dst_a, align 8\n";
                oss << "    " << t << ".dst_b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << current_res_ptr_ << ", i32 0, i32 1\n";
                oss << "    store i64 " << t << ".b, i64* " << t << ".dst_b, align 8\n";
                oss << "    " << t << ".dst_s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << current_res_ptr_ << ", i32 0, i32 2\n";
                oss << "    store i32 " << t << ".s, i64* " << t << ".dst_s, align 4\n";
            }
            oss << "    ret void\n";
        }
    }, stmt->data);
}

std::string LLVMEmitter::emit_llvm_expr(Expr* expr, std::ostringstream& oss) {
    if (!expr) return "@TAFPU_ZERO";

    std::string res_ptr = next_temp();

    std::visit([&](const auto& e) {
        using T = std::decay_t<decltype(e)>;

        if constexpr (std::is_same_v<T, IntLiteralExpr>) {
            oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";
            std::string t = next_temp();
            oss << "    " << t << ".a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 0\n";
            oss << "    store i64 " << e.value << ", i64* " << t << ".a, align 8\n";
            oss << "    " << t << ".b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 1\n";
            oss << "    store i64 0, i64* " << t << ".b, align 8\n";
            oss << "    " << t << ".s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 2\n";
            oss << "    store i32 0, i32* " << t << ".s, align 4\n";
        }
        else if constexpr (std::is_same_v<T, TryteLiteralExpr>) {
            oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";
            std::string t = next_temp();
            oss << "    " << t << ".a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 0\n";
            oss << "    store i64 " << e.value << ", i64* " << t << ".a, align 8\n";
            oss << "    " << t << ".b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 1\n";
            oss << "    store i64 0, i64* " << t << ".b, align 8\n";
            oss << "    " << t << ".s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 2\n";
            oss << "    store i32 0, i32* " << t << ".s, align 4\n";
        }
        else if constexpr (std::is_same_v<T, TafpuLiteralExpr>) {
            oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";
            std::string t = next_temp();
            oss << "    " << t << ".a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 0\n";
            oss << "    store i64 " << e.value.a << ", i64* " << t << ".a, align 8\n";
            oss << "    " << t << ".b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 1\n";
            oss << "    store i64 " << e.value.b << ", i64* " << t << ".b, align 8\n";
            oss << "    " << t << ".s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 2\n";
            oss << "    store i32 " << e.value.s << ", i32* " << t << ".s, align 4\n";
        }
        else if constexpr (std::is_same_v<T, IdentifierExpr>) {
            auto it = llvm_vars_.find(e.name);
            if (it != llvm_vars_.end()) {
                res_ptr = it->second;
            } else {
                res_ptr = "@TAFPU_ZERO";
            }
        }
        else if constexpr (std::is_same_v<T, UnaryExpr>) {
            std::string op_ptr = emit_llvm_expr(e.operand, oss);
            oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";
            if (e.op == UnaryOp::NEG) {
                oss << "    call void @tafpu_sub_native(%struct.TafpuNum* " << res_ptr << ", %struct.TafpuNum* @TAFPU_ZERO, %struct.TafpuNum* " << op_ptr << ")\n";
            }
        }
        else if constexpr (std::is_same_v<T, BinaryExpr>) {
            std::string left_ptr = emit_llvm_expr(e.left, oss);
            std::string right_ptr = emit_llvm_expr(e.right, oss);
            oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";

            switch (e.op) {
                case BinaryOp::ADD:
                    oss << "    call void @tafpu_add_native(%struct.TafpuNum* " << res_ptr << ", %struct.TafpuNum* " << left_ptr << ", %struct.TafpuNum* " << right_ptr << ")\n";
                    break;
                case BinaryOp::SUB:
                    oss << "    call void @tafpu_sub_native(%struct.TafpuNum* " << res_ptr << ", %struct.TafpuNum* " << left_ptr << ", %struct.TafpuNum* " << right_ptr << ")\n";
                    break;
                case BinaryOp::MUL:
                case BinaryOp::MATMUL:
                    oss << "    call void @tafpu_mul_native(%struct.TafpuNum* " << res_ptr << ", %struct.TafpuNum* " << left_ptr << ", %struct.TafpuNum* " << right_ptr << ")\n";
                    break;
                case BinaryOp::EQ:
                case BinaryOp::NEQ:
                case BinaryOp::LT:
                case BinaryOp::LE:
                case BinaryOp::GT:
                case BinaryOp::GE: {
                    std::string t = next_temp();
                    oss << "    " << t << ".cmp = call i32 @tafpu_cmp_native(%struct.TafpuNum* " << left_ptr << ", %struct.TafpuNum* " << right_ptr << ")\n";
                    std::string cond_name = (e.op == BinaryOp::EQ) ? "eq" : (e.op == BinaryOp::NEQ) ? "ne" : (e.op == BinaryOp::LT) ? "slt" : (e.op == BinaryOp::LE) ? "sle" : (e.op == BinaryOp::GT) ? "sgt" : "sge";
                    oss << "    " << t << ".bool = icmp " << cond_name << " i32 " << t << ".cmp, 0\n";
                    oss << "    " << t << ".i64 = zext i1 " << t << ".bool to i64\n";
                    oss << "    " << t << ".a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 0\n";
                    oss << "    store i64 " << t << ".i64, i64* " << t << ".a, align 8\n";
                    oss << "    " << t << ".b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 1\n";
                    oss << "    store i64 0, i64* " << t << ".b, align 8\n";
                    oss << "    " << t << ".s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 2\n";
                    oss << "    store i32 0, i32* " << t << ".s, align 4\n";
                    break;
                }
                default:
                    oss << "    call void @tafpu_add_native(%struct.TafpuNum* " << res_ptr << ", %struct.TafpuNum* " << left_ptr << ", %struct.TafpuNum* " << right_ptr << ")\n";
                    break;
            }
        }
        else if constexpr (std::is_same_v<T, CallExpr>) {
            if (e.callee == "print" || e.callee == "println") {
                if (!e.args.empty()) {
                    Expr* arg = e.args[0];
                    if (std::holds_alternative<StringLiteralExpr>(arg->data)) {
                        const auto& str = std::get<StringLiteralExpr>(arg->data);
                        std::string gstr = "@.str." + std::to_string(++str_id_);
                        llvm_strings_.push_back({gstr, str.value});
                        oss << "    call i32 @puts(i8* getelementptr inbounds ([" << (str.value.size() + 1) << " x i8], [" << (str.value.size() + 1) << " x i8]* " << gstr << ", i32 0, i32 0))\n";
                    } else {
                        std::string val_ptr = emit_llvm_expr(arg, oss);
                        std::string t = next_temp();
                        oss << "    " << t << ".a_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << val_ptr << ", i32 0, i32 0\n";
                        oss << "    " << t << ".a = load i64, i64* " << t << ".a_ptr, align 8\n";
                        oss << "    call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([6 x i8], [6 x i8]* @.fmt_i64, i32 0, i32 0), i64 " << t << ".a)\n";
                    }
                }
                res_ptr = "@TAFPU_ZERO";
            }
            else if (e.callee == "setun2d_is_running") {
                oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";
                std::string t = next_temp();
                oss << "    " << t << ".r = call i32 @setun2d_is_running()\n";
                oss << "    " << t << ".i64 = sext i32 " << t << ".r to i64\n";
                oss << "    " << t << ".a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 0\n";
                oss << "    store i64 " << t << ".i64, i64* " << t << ".a, align 8\n";
                oss << "    " << t << ".b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 1\n";
                oss << "    store i64 0, i64* " << t << ".b, align 8\n";
                oss << "    " << t << ".s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 2\n";
                oss << "    store i32 0, i32* " << t << ".s, align 4\n";
            }
            else if (e.callee == "setun2d_flip") {
                oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";
                std::string t = next_temp();
                oss << "    " << t << ".k = call i32 @setun2d_flip()\n";
                oss << "    " << t << ".i64 = sext i32 " << t << ".k to i64\n";
                oss << "    " << t << ".a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 0\n";
                oss << "    store i64 " << t << ".i64, i64* " << t << ".a, align 8\n";
                oss << "    " << t << ".b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 1\n";
                oss << "    store i64 0, i64* " << t << ".b, align 8\n";
                oss << "    " << t << ".s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 2\n";
                oss << "    store i32 0, i32* " << t << ".s, align 4\n";
            }
            else if (e.callee == "setun2d_get_key") {
                oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";
                std::string t = next_temp();
                oss << "    " << t << ".k = call i32 @setun2d_get_key()\n";
                oss << "    " << t << ".i64 = sext i32 " << t << ".k to i64\n";
                oss << "    " << t << ".a = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 0\n";
                oss << "    store i64 " << t << ".i64, i64* " << t << ".a, align 8\n";
                oss << "    " << t << ".b = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 1\n";
                oss << "    store i64 0, i64* " << t << ".b, align 8\n";
                oss << "    " << t << ".s = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* " << res_ptr << ", i32 0, i32 2\n";
                oss << "    store i32 0, i32* " << t << ".s, align 4\n";
            }
            else {
                // Generic user-defined function call
                oss << "    " << res_ptr << " = alloca %struct.TafpuNum, align 8\n";
                std::vector<std::string> arg_ptrs;
                for (Expr* a : e.args) {
                    arg_ptrs.push_back(emit_llvm_expr(a, oss));
                }
                oss << "    call void @" << e.callee << "(%struct.TafpuNum* " << res_ptr;
                for (const auto& ap : arg_ptrs) {
                    oss << ", %struct.TafpuNum* " << ap;
                }
                oss << ")\n";
            }
        }
        else {
            res_ptr = "@TAFPU_ZERO";
        }
    }, expr->data);

    return res_ptr;
}

std::string LLVMEmitter::emit_llvm_ir(const Program& program) {
    std::ostringstream body_oss;
    temp_id_ = 0;
    label_counter_ = 0;
    str_id_ = 0;
    llvm_vars_.clear();
    llvm_strings_.clear();

    // Emit user functions
    bool has_user_main = false;
    std::vector<Stmt*> top_stmts;
    for (Stmt* s : program.statements) {
        if (std::holds_alternative<FnDeclStmt>(s->data)) {
            const auto& fn = std::get<FnDeclStmt>(s->data);
            if (fn.name == "main") has_user_main = true;
            emit_llvm_function(s, body_oss);
        } else {
            top_stmts.push_back(s);
        }
    }

    // Emit main entry function
    body_oss << "define i32 @main(i32 %argc, i8** %argv) {\n";
    body_oss << "entry:\n";
    current_res_ptr_ = "";

    for (Stmt* s : top_stmts) {
        emit_llvm_stmt(s, body_oss);
    }

    if (has_user_main) {
        body_oss << "    %main_ret = alloca %struct.TafpuNum, align 8\n";
        body_oss << "    call void @stn_main(%struct.TafpuNum* %main_ret)\n";
        body_oss << "    %m.a_ptr = getelementptr inbounds %struct.TafpuNum, %struct.TafpuNum* %main_ret, i32 0, i32 0\n";
        body_oss << "    %m.a = load i64, i64* %m.a_ptr, align 8\n";
        body_oss << "    %ret_code = trunc i64 %m.a to i32\n";
        body_oss << "    ret i32 %ret_code\n";
    } else {
        body_oss << "    ret i32 0\n";
    }
    body_oss << "}\n";

    // Build header with declarations and string constants
    std::ostringstream header_oss;
    emit_llvm_global_decls(header_oss);

    for (const auto& [name, val] : llvm_strings_) {
        header_oss << name << " = private unnamed_addr constant [" << (val.size() + 1) << " x i8] c\"" << val << "\\00\", align 1\n";
    }
    header_oss << "\n";

    return header_oss.str() + body_oss.str();
}

// ============================================================================
// 3. Direct Native Compilation Pipeline (.exe / binary)
// ============================================================================

bool LLVMEmitter::compile_native(const Program& program, const std::string& output_path, int opt_level) {
    config_.opt_level = opt_level;
    std::string native_c = emit_native_c(program);

    std::string temp_c_file = output_path + ".tmp.cpp";
    {
        std::ofstream ofs(temp_c_file);
        if (!ofs.is_open()) return false;
        ofs << native_c;
    }

    const char* env_home = std::getenv("SETUN_HOME");
    std::string home_inc = env_home ? (std::string(" -I\"") + env_home + "/include\" -I\"" + env_home + "/Code/include\"") : "";

    std::ostringstream cmd;
    cmd << "g++ -std=c++20 -O" << opt_level 
        << " -Iinclude -I\"../include\" -I\"Code/include\" -I\"Compiler/Code/include\" -I\"../Code/include\" -I\"../../Compiler/Code/include\""
        << home_inc << " \"" 
        << temp_c_file << "\" -o \"" << output_path << "\"";

    int ret = std::system(cmd.str().c_str());
    if (ret == 0) {
        std::remove(temp_c_file.c_str());
    }
    return (ret == 0);
}

// ============================================================================
// 4. Pure LLVM AOT Compilation Pipeline (.ll -> .exe via LLVM/Clang)
// ============================================================================

bool LLVMEmitter::compile_llvm_native(const Program& program, const std::string& output_path, int opt_level) {
    config_.opt_level = opt_level;
    std::string llvm_ir = emit_llvm_ir(program);

    std::string ll_file = output_path + ".ll";
    {
        std::ofstream ofs(ll_file);
        if (!ofs.is_open()) return false;
        ofs << llvm_ir;
    }

    // Try compiling with clang if available
    std::ostringstream clang_cmd;
    clang_cmd << "clang -O" << opt_level << " \"" << ll_file << "\" -o \"" << output_path << "\" 2>nul";
    int ret = std::system(clang_cmd.str().c_str());

    if (ret == 0) {
        std::cout << "  -> [LLVM Backend] Successfully compiled via Clang/LLVM!\n";
        return true;
    }

    // Fallback: If clang is not found, compile through GCC native pipeline while keeping the .ll file
    std::cout << "  -> [Note] Clang not found in PATH; LLVM IR exported to " << ll_file << "\n";
    return compile_native(program, output_path, opt_level);
}

} // namespace setun
