// ============================================================================
// OpenQASM 3.0 Generated by Tersun 1.0.2 Quantum Compiler (QVM)
// Circuit: tersun_native_qasm (16 Qubits)
// ============================================================================

OPENQASM 3.0;
include "stdgates.inc";

// Quantum and Classical Register Declarations
qubit[16] q;
bit[16] c;

cx q[1], q[0];
cx q[2], q[4];
cx q[6], q[5];
cx q[4], q[3];
cx q[2], q[7];
cx q[0], q[8];
cx q[0], q[9];
cx q[7], q[10];
cx q[9], q[0];
cx q[10], q[0];
cx q[2], q[11];
x q[12];
cx q[11], q[2];
cx q[12], q[2];
cx q[0], q[0];
cx q[16], q[14];
cx q[17], q[15];
cx q[14], q[13];
cx q[13], q[18];
cx q[20], q[19];
cx q[22], q[21];
cx q[24], q[23];
x q[25];
x q[26];
h q[16];
cx q[25], q[16];
x q[27];
x q[28];
// Tersun Ternary Invert (+1 <-> -1)
z q[28];
h q[17];
cx q[27], q[17];
cx q[16], q[30];
cx q[30], q[29];
cx q[17], q[31];
cx q[31], q[29];
cx q[33], q[32];
cx q[29], q[35];
cx q[35], q[34];
x q[37];
cx q[37], q[36];
cx q[16], q[39];
cx q[17], q[40];
cx q[39], q[38];
cx q[38], q[36];
x q[41];
cx q[41], q[36];
x q[42];
cx q[42], q[36];
cx q[45], q[44];
cx q[44], q[43];
x q[46];
cx q[46], q[43];
cx q[48], q[47];
cx q[43], q[50];
cx q[50], q[49];
cx q[29], q[52];
cx q[52], q[51];
cx q[55], q[54];
x q[0];

// Projective Measurement into Classical Register
c = measure q;
