// ============================================================================
// Automatically generated by Setun 2.0 Native AOT Transpiler
// Target: x86_64-pc-windows-msvc (Opt Level: -O3)
// ============================================================================

#include "compiler/native_runtime.hpp"
#include <iostream>
#include <string>
#include <cstdint>
#include <cassert>
#include <stdexcept>

using namespace setun::runtime;

template<typename T>
static inline std::ostream& print_val_stream(std::ostream& os, const T& val) {
    if constexpr (std::is_same_v<std::decay_t<T>, TafpuNum_C>) {
        return os << val.to_double();
    } else {
        return os << val;
    }
}

template<typename T>
static inline bool is_truthy(const T& val) {
    if constexpr (std::is_same_v<std::decay_t<T>, TafpuNum_C>) {
        return val.to_double() != 0.0;
    } else if constexpr (std::is_same_v<std::decay_t<T>, bool>) {
        return val;
    } else {
        return static_cast<bool>(val);
    }
}

int64_t fib(int64_t n);
void stn_main();

int64_t fib(int64_t n) {
    {
        auto r = TafpuNum_C(0, 0, 0);
        if (is_truthy(TafpuNum_C(tafpu_cmp_c(n, TafpuNum_C(2, 0, 0)) < 0 ? 1 : 0, 0, 0))) {
            {
                r = n;
            }
        } else {
            {
                r = tafpu_add_c(fib(tafpu_sub_c(n, TafpuNum_C(1, 0, 0))), fib(tafpu_sub_c(n, TafpuNum_C(2, 0, 0))));
            }
        }
        return r;
    }
    return 0;
}

void stn_main() {
    {
        auto sink = TafpuNum_C(0, 0, 0);
        {
            int64_t __i = 0;
            int64_t __stop = TafpuNum_C(200, 0, 0);
            int64_t __step = 1;
            while ((__step > 0 && __i < __stop) || (__step < 0 && __i > __stop)) {
                int64_t k = __i;
                {
                    sink = tafpu_add_c(sink, fib(TafpuNum_C(24, 0, 0)));
                }
                __i += __step;
            }
        }
        (print_val_stream(std::cout, sink) << '\n');
    }
}

int main(int argc, char** argv) {
    (void)argc; (void)argv;
    // Setun Native Execution Entry
    stn_main();
    return 0;
}
