// ============================================================================
// OpenQASM 3.0 Generated by Tersun 1.0.2 Quantum Compiler (QVM)
// Circuit: tersun_native_qasm (16 Qubits)
// ============================================================================

OPENQASM 3.0;
include "stdgates.inc";

// Quantum and Classical Register Declarations
qubit[16] q;
bit[16] c;

x q[1];
cx q[0], q[3];
cx q[1], q[4];
cx q[3], q[2];
cx q[4], q[2];
cx q[2], q[0];

// Projective Measurement into Classical Register
c = measure q;
